import mongoose from 'mongoose';

const clientSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  name: String,
  email: String,
  phone: String,
  tags: [String], // VIP, ongoing, potential
  source: { type: String, default: 'Manual' }, // LinkedIn, Upwork, Fiverr, Email, Web Form
  notes: String,
  linkedinUrl: String,
  upworkUrl: String,
  fiverrUrl: String,
  autoGenerated: { type: Boolean, default: false },
  onboardingCompleted: { type: Boolean, default: false },
  welcomeEmailSent: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

export default mongoose.model('Client', clientSchema);
